#!/bin/sh

# 現在のブランチ名を取得
branch=$(git rev-parse --abbrev-ref HEAD)

# main, qaブランチではpushできません。
if [ "$branch" = "main" ] || [ "$branch" = "qa" ]; then
  echo "❌ Pushing directly to the $branch branch is not allowed. Please create a pull request."
  exit 1
fi

echo "✔ Check complete"
exit 0
