#!/bin/sh

# 現在のブランチ名を取得
branch=$(git rev-parse --abbrev-ref HEAD)

# main, qaブランチではmerge commitできません。
if [ "$branch" = "main" ] || [ "$branch" = "qa" ]; then
  echo "❌ Merge commits are prohibited on the $branch branch."
  exit 1
fi

echo "✔ Check complete"
exit 0
